---
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  roles:
    - common
    - docker-ce
    - system-upgrade
    - role: user-accounts
      createusers:
      - pup
    - dotfiles
