- name: Clone dotfiles repo.
  git: repo=https://github.com/duckinator/dotfiles.git version=main dest=/home/pup/dotfiles
  become: yes
  become_user: pup

- name: Install Emanate
  command: pip3 install emanate

- name: Set up dotfiles.
  command: emanate --no-confirm
  args:
    chdir: /home/pup/dotfiles
  become: yes
  become_user: pup
