- name: Clone dotfiles repo.
  git: repo=https://github.com/duckinator/dotfiles.git version=main dest=/home/pup/dotfiles
  become: yes
  become_user: pup

- name: Install Emanate (Fedora)
  dnf:
    name: emanate
    state: present
  when: ansible_distribution == "Fedora"

- name: Install Emanate
  command: pip3 install --user emanate
  become: yes
  become_user: pup
  when: ansible_distribution != "Fedora"

# For now, only automatically set up dotfiles on Fedora.
- name: Set up dotfiles.
  command: emanate --no-confirm --source /home/pup/dotfiles --destination /home/pup/
  become: yes
  become_user: pup
  when: ansible_distribution == "Fedora"
