- name: Clone dotfiles repo.
  git: repo=https://github.com/duckinator/dotfiles.git version=main dest=/home/pup/dotfiles
  become: yes
  become_user: pup

- name: Set up dotfiles.
  command: /home/pup/dotfiles/bin/dotfiles-bootstrap.py
  become: yes
  become_user: pup
