- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present

#- name: Add Docker CE repository
#  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Add Docker CE repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo --set-enabled docker-ce-test
