- name: Install common packages
  apt:
    name:
      - curl
      - firefox
      - git
      - hexchat
      - htop
      - neovim
      - ruby
      - python3
      - sudo
      - tmux
      - tree
      - xclip
      - onboard
    state: present
