- name: Install common packages
  apt:
    name:
      - bat
      - curl
      - firefox
      - git
      - hexchat
      - htop
      - kicad
      - neovim
      - openscad
      - onboard
      - python3
      - python3-pynvim
      - ruby
      - sudo
      - tmux
      - tree
      - xclip
    state: present
