- name: Add contrib repositories
  ansible.builtin.command:
    #cmd: "apt-add-repository -y contrib non-free"
    cmd: "apt-add-repository -y contrib"

- name: Install common packages
  apt:
    name:
      - bat
      - curl
      - firefox-esr
      - git
      - hexchat
      - htop
      - kicad
      - neovim
      - openscad
      - onboard
      - python3
      - python3-pynvim
      - ruby
      - sudo
      - tmux
      - tree
      - xclip
    state: present

- name: Enable multi-arch support (x86-64 only)
  ansible.builtin.command:
    cmd: dpkg --add-architecture i386
  when: ansible_architecture == "x86_64"

- name: Install steam-installer (x86-64 only)
  apt:
    name:
      - steam-installer
