- name: Add contrib repositories
  ansible.builtin.command:
    #cmd: "apt-add-repository -y contrib non-free"
    cmd: "apt-add-repository -y contrib"

- name: Enable multi-arch support (x86-64 only)
  ansible.builtin.command:
    cmd: dpkg --add-architecture i386
  when: ansible_architecture == "x86_64"

- name: Update apt cache
  apt:
    update_cache: true

- name: Install common packages
  apt:
    name:
      - bat
      - build-essential
      - clang
      - crun
      - curl
      - firefox-esr
      - git
      - hexchat
      - htop
      - keepassxc
      - kicad
      - krita
      - liferea
      - meson
      - neovim
      - ninja-build
      - obs-studio
      - openscad
      - onboard
      - pandoc
      - pipewire
      - pipx
      - podman
      - python3
      - python3-pynvim
      - python3-termcolor
      - python3-venv
      - ruby
      - sudo
      - tigervnc-viewer
      - tmux
      - tree
      - virt-manager
      - xclip
    state: present

- name: Install packages for Android development
  apt:
    name:
      - adb
      - android-sdk-platform-tools
      - sdkmanager

- name: Install steam-installer (x86-64 only)
  apt:
    name:
      - steam-installer
