# TODO: If I decide I care enough:
# - install Signal from OpenSUSE repos, since they kindly provide a Fedora package for it!

- name: Install workstation and RPM Fusion repos
  dnf:
    name:
          - fedora-workstation-repositories
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: Install common packages
  dnf:
      name:
          - cura
          - firefox
          - git
          - hexchat
          - htop
          - kicad
          - mlocate
          - moby-engine
          - neovim
          - openscad
          - python3
          - ruby
          - xfce4-terminal
          - flatpak
          - sudo
          - tmux
          - tree
          - xclip
          - discord # Provided by rpmfusion-nonfree
      state: "present"

- name: Enable third-party dnf repositories
  command: dnf config-manager --set-enabled {{ item }}
  loop:
    - rpmfusion-nonfree-steam
