- name: Enable audio
  community.general.sysrc:
    name: snd_hda_load
    value: "YES"
    path: /boot/loader.conf

- name: Enable bluetooth
  community.general.sysrc:
    name: ng_ubt_load
    value: "YES"
    path: /boot/loader.conf

# Lets you get temperature info for Intel CPUs.
- name: Auto-load coretemp module
  community.general.sysrc:
    name: coretemp_load
    value: "YES"
    path: /boot/loader.conf

# Lets you get temperature info for AMD CPUs.
- name: Auto-load amdtemp module
  community.general.sysrc:
    name: amdtemp_load
    value: "YES"
    path: /boot/loader.conf

- name: Enable Linux compatability layer
  community.general.sysrc:
    name: linux_enable
    value: "YES"
    path: /etc/rc.conf

# Needed so we can install Linux compatibility packages
- name: Start Linux compatibility
  service:
    name: linux
    state: started

- name: Enable D-Bus
  community.general.sysrc:
    name: dbus_enable
    value: "YES"
    path: /etc/rc.conf

- name: Enable /proc
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "proc			/proc   	procfs  rw              0       0"
    state: present

- name: Enable linsysfs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "linsysfs	/compat/linux/sys 	procfs	rw		0	0"

- name: Install common packages
  community.general.pkgng:
    name:
      - bat
      - bash
      - firefox
      - git
      - hexchat
      - htop
      - kicad
      - neovim
      - openscad
      - python3
      - py39-pynvim
      - ruby
      - sudo
      - tmux
      - tree
      - xclip
      - emulators/linux_base-c7
      - xorg
      - xfce
      - signal-desktop
    state: present

- name: Install pip3
  command: python3 -m ensurepip

# There's no ruby-gems metapackage, only ruby<version>-gems, so we have to
# do some gross, hacky garbage to install rubygems automagically.
- name: Install rubygems.
  shell: "pkg install $(/usr/local/bin/ruby --version | cut -d '.' -f 1-2 | sed 's/[ .]//g')-gems"
  environment:
    ASSUME_ALWAYS_YES: "yes"
