- name: Distribution-specific tasks
  include_tasks: "main-{{ ansible_distribution.replace('/', '-').replace(' ', '-') }}.yml"

- name: Configure and install Flatpak
  include_tasks: "flatpak.yml"
  when: ansible_distribution != "FreeBSD"
