- name: Add contrib and non-free repositories
  ansible.builtin.command:
    #cmd: "apt-add-repository -y contrib non-free"
    cmd: "apt-add-repository -y contrib"

- name: Install common packages
  apt:
    name:
      - bat
      - curl
      - firefox-esr
      - git
      - hexchat
      - htop
      - kicad
      - neovim
      - openscad
      - onboard
      - python3
      - python3-pynvim
      - ruby
      - sudo
      - steam-installer
      - tmux
      - tree
      - xclip
    state: present
