- name: Install common packages
  dnf:
      name: "{{ item }}"
      state: "present"
  with_items:
    - firefox
    - fish
    - git
    - hexchat
    - htop
    - neovim
    - openscad
    - python2-libselinux
    - ruby
    - sudo
    - tmux
    - tree
    - xclip

# TODO: Make less hacky.
- name: Install python2-libselinux if needed.
  dnf:
    name:
      - python2-libselinux
  when: ansible_distribution_major_version == "28"
