- name: Install common packages
  pkgng:
    name:
      - bash
      - firefox
      - git
      - hexchat
      - htop
      - kicad
      - neovim
      - openscad
      - python3
      - ruby
      - rxvt-unicode
      - sudo
      - tmux
      - tree
      - xclip
      - x11/kde5
      - x11/sddm
      - emulators/linux_base-c7
    state: present

- name: Install pip3
  command: python3 -m ensurepip

# There's no ruby-gems metapackage, only ruby<version>-gems, so we have to
# do some gross, hacky garbage to install rubygems automagically.
- name: Install rubygems.
  shell: "pkg install $(/usr/local/bin/ruby --version | cut -d '.' -f 1-2 | sed 's/[ .]//g')-gems"
  environment:
    ASSUME_ALWAYS_YES: "yes"

- name: Enable audio
  lineinfile:
    path: /boot/loader.conf
    line: "snd_hda_load=\"YES\""
    state: present

- name: Enable bluetooth
  lineinfile:
    path: /boot/loader.conf
    line: "ng_ubt_load=\"YES\""
    state: present

- name: Enable Linux compatability layer
  lineinfile:
    path: /etc/rc.conf
    line: "linux_enable=\"YES\""
    state: present

- name: Enable D-Bus
  lineinfile:
    path: /etc/rc.conf
    line: "dbus_enable=\"YES\""
    state: present

- name: Enable HAL
  lineinfile:
    path: /etc/rc.conf
    line: "hald_enable=\"YES\""
    state: present

- name: Enable SDDM
  lineinfile:
    path: /etc/rc.conf
    line: "sddm_enable=\"YES\""
    state: present
