- name: Install common packages
  dnf:
      name: "{{ item }}"
      state: "present"
  with_items:
    - cura
    - firefox
    - fish
    - git
    - hexchat
    - htop
    - mlocate
    - neovim
    - openscad
    - python3
    - ruby
    - rxvt-unicode
    - flatpak
    - sudo
    - tmux
    - tree
    - xclip
    - fedora-workstation-repositories

- name: Enable third-party dnf repositories
  command: dnf config-manager --set-enabled {{ item }}
  loop:
    - google-chrome
    - rpmfusion-free
    - rpmfusion-free-updates
    - rpmfusion-nonfree-steam

- name: Install python2-libselinux if needed.
  dnf:
    name:
      - python2-libselinux
  when: ansible_distribution_major_version == "28"
