- name: Install common packages
  dnf:
      name:
          - cura
          - firefox
          - fish
          - git
          - hexchat
          - htop
          - kicad
          - mlocate
          - moby-engine
          - neovim
          - openscad
          - python3
          - ruby
          - rxvt-unicode
          - flatpak
          - sudo
          - tmux
          - tree
          - xclip
          - fedora-workstation-repositories
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
      state: "present"

- name: Enable third-party dnf repositories
  command: dnf config-manager --set-enabled {{ item }}
  loop:
    - rpmfusion-nonfree-steam

- name: Install python2-libselinux if needed.
  dnf:
    name:
      - python2-libselinux
  when: ansible_distribution_major_version == "28"
