- name: Install common packages
  apt:
      name: "{{ item }}"
      state: "present"
  with_items:
    - firefox-esr
    - fish
    - git
    - hexchat
    - htop
    - neovim
    - ruby
    - sudo
    - tmux
    - tree
    - xclip
    - onboard
