- name: Install common packages
  dnf:
      name: "{{ item }}"
      state: "present"
  with_items:
    - cura
    - firefox
    - fish
    - git
    - hexchat
    - htop
    - neovim
    - openscad
    - ruby
    - sudo
    - tmux
    - tree
    - xclip
    - python3

- name: Install python2-libselinux if needed.
  dnf:
    name:
      - python2-libselinux
  when: ansible_distribution_major_version == "28"
