- name: Copy sudo config
  copy:
    src: roles/user-accounts/files/
    dest: /

- name: Ensure group "sudo" exists
  group:
    name: sudo
    state: present

- name: Adding users
  user:
    name: "{{ item }}"
    groups: "{{ user_accounts[item].groups }}"
    append: yes
    generate_ssh_key: yes
    shell: "{{ user_accounts[item].shell[dist_codename] }}"
    state: present
  with_items: "{{ create_users }}"
  register: users

- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ user_accounts[item].key }}"
    state: present
  with_items: "{{ create_users }}"

- name: Expiring Passwords for new users (Linux)
  command: "passwd -e {{ item.item }}"
  with_items: "{{ users.results }}"
  when: item|changed and not dist_codename|search("bsd")

- name: Expiring Passwords for new users (FreeBSD)
  command: "pw usermod {{ item.item }} -p -1"
  with_items: "{{ users.results }}"
  when: item|changed and dist_codename|search("freebsd")
