- name: Copy sudo config
  copy:
    src: roles/user-accounts/files
    dest: /

- name: Adding users
  user:
    name: "{{ item }}"
    groups: "{{ user_accounts[item].groups }}"
    append: yes
    generate_ssh_key: yes
    shell: "{{ user_accounts[item].shell[dist_codename] }}"
    state: present
  with_items: "{{ create_users }}"
  register: users

- name: Add authorized keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ user_accounts[item].key }}"
    state: present
  with_items: "{{ create_users }}"

- name: Expiring Passwords for new users (Linux)
  command: "passwd -d -e {{ item.item.key }}"
  #when: item|changed
  with_items: "{{ users.results }}"
  when: not dist_codename | search("bsd")

- name: Expiring Passwords for new users (FreeBSD)
  command: "pw usermod {{ item.item }} -p -1"
  #when: item|changed
  with_items: "{{ users.results }}"
  when: dist_codename | search("freebsd")
